AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

CyclomaticComplexity:
  Max: 7

Gemspec/OrderedDependencies:
  Enabled: false

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

LineLength:
  Max: 180

ClassLength:
  Max: 200

ModuleLength:
  Max: 200

MethodLength:
  Max: 50

BlockLength:
  Max: 50
  Exclude:
    - Rakefile
    - '**/*.rake'
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

FileName:
  Exclude:
    - Capfile

Metrics/AbcSize:
  Max: 40
